# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/circleci/openjdk:8-jdk-browsers
     
      
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.3-alpine
      environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/podam

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key:podam-{{ checksum "pom.xml" }}
          
          
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: podam--{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
          
      - store_artifacts:
          path: target/podam-0.0.1-SNAPSHOT.jar



